/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by MockGen. DO NOT EDIT.
// Source: ../dnsrecordset.go
//
// Generated by this command:
//
//	mockgen -package mock -destination=dnsrecordset.go -source=../dnsrecordset.go github.com/k-orc/openstack-resource-controller/internal/osclients/mock DNSRecordsetClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	iter "iter"
	reflect "reflect"

	recordsets "github.com/gophercloud/gophercloud/v2/openstack/dns/v2/recordsets"
	gomock "go.uber.org/mock/gomock"
)

// MockDNSRecordsetClient is a mock of DNSRecordsetClient interface.
type MockDNSRecordsetClient struct {
	ctrl     *gomock.Controller
	recorder *MockDNSRecordsetClientMockRecorder
	isgomock struct{}
}

// MockDNSRecordsetClientMockRecorder is the mock recorder for MockDNSRecordsetClient.
type MockDNSRecordsetClientMockRecorder struct {
	mock *MockDNSRecordsetClient
}

// NewMockDNSRecordsetClient creates a new mock instance.
func NewMockDNSRecordsetClient(ctrl *gomock.Controller) *MockDNSRecordsetClient {
	mock := &MockDNSRecordsetClient{ctrl: ctrl}
	mock.recorder = &MockDNSRecordsetClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDNSRecordsetClient) EXPECT() *MockDNSRecordsetClientMockRecorder {
	return m.recorder
}

// CreateRecordset mocks base method.
func (m *MockDNSRecordsetClient) CreateRecordset(ctx context.Context, zoneID string, opts recordsets.CreateOptsBuilder) (*recordsets.RecordSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRecordset", ctx, zoneID, opts)
	ret0, _ := ret[0].(*recordsets.RecordSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRecordset indicates an expected call of CreateRecordset.
func (mr *MockDNSRecordsetClientMockRecorder) CreateRecordset(ctx, zoneID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRecordset", reflect.TypeOf((*MockDNSRecordsetClient)(nil).CreateRecordset), ctx, zoneID, opts)
}

// DeleteRecordset mocks base method.
func (m *MockDNSRecordsetClient) DeleteRecordset(ctx context.Context, zoneID, recordsetID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecordset", ctx, zoneID, recordsetID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecordset indicates an expected call of DeleteRecordset.
func (mr *MockDNSRecordsetClientMockRecorder) DeleteRecordset(ctx, zoneID, recordsetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecordset", reflect.TypeOf((*MockDNSRecordsetClient)(nil).DeleteRecordset), ctx, zoneID, recordsetID)
}

// GetRecordset mocks base method.
func (m *MockDNSRecordsetClient) GetRecordset(ctx context.Context, zoneID, recordsetID string) (*recordsets.RecordSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordset", ctx, zoneID, recordsetID)
	ret0, _ := ret[0].(*recordsets.RecordSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecordset indicates an expected call of GetRecordset.
func (mr *MockDNSRecordsetClientMockRecorder) GetRecordset(ctx, zoneID, recordsetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordset", reflect.TypeOf((*MockDNSRecordsetClient)(nil).GetRecordset), ctx, zoneID, recordsetID)
}

// ListRecordsets mocks base method.
func (m *MockDNSRecordsetClient) ListRecordsets(ctx context.Context, zoneID string, opts recordsets.ListOptsBuilder) iter.Seq2[*recordsets.RecordSet, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecordsets", ctx, zoneID, opts)
	ret0, _ := ret[0].(iter.Seq2[*recordsets.RecordSet, error])
	return ret0
}

// ListRecordsets indicates an expected call of ListRecordsets.
func (mr *MockDNSRecordsetClientMockRecorder) ListRecordsets(ctx, zoneID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecordsets", reflect.TypeOf((*MockDNSRecordsetClient)(nil).ListRecordsets), ctx, zoneID, opts)
}

// UpdateRecordset mocks base method.
func (m *MockDNSRecordsetClient) UpdateRecordset(ctx context.Context, zoneID, recordsetID string, opts recordsets.UpdateOptsBuilder) (*recordsets.RecordSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRecordset", ctx, zoneID, recordsetID, opts)
	ret0, _ := ret[0].(*recordsets.RecordSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRecordset indicates an expected call of UpdateRecordset.
func (mr *MockDNSRecordsetClientMockRecorder) UpdateRecordset(ctx, zoneID, recordsetID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecordset", reflect.TypeOf((*MockDNSRecordsetClient)(nil).UpdateRecordset), ctx, zoneID, recordsetID, opts)
}
