/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DNSRecordsetResourceStatusApplyConfiguration represents a declarative configuration of the DNSRecordsetResourceStatus type for use
// with apply.
type DNSRecordsetResourceStatusApplyConfiguration struct {
	Name        *string  `json:"name,omitempty"`
	Type        *string  `json:"type,omitempty"`
	Records     []string `json:"records,omitempty"`
	TTL         *int32   `json:"ttl,omitempty"`
	Description *string  `json:"description,omitempty"`
	Status      *string  `json:"status,omitempty"`
}

// DNSRecordsetResourceStatusApplyConfiguration constructs a declarative configuration of the DNSRecordsetResourceStatus type for use with
// apply.
func DNSRecordsetResourceStatus() *DNSRecordsetResourceStatusApplyConfiguration {
	return &DNSRecordsetResourceStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DNSRecordsetResourceStatusApplyConfiguration) WithName(value string) *DNSRecordsetResourceStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *DNSRecordsetResourceStatusApplyConfiguration) WithType(value string) *DNSRecordsetResourceStatusApplyConfiguration {
	b.Type = &value
	return b
}

// WithRecords adds the given value to the Records field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Records field.
func (b *DNSRecordsetResourceStatusApplyConfiguration) WithRecords(values ...string) *DNSRecordsetResourceStatusApplyConfiguration {
	for i := range values {
		b.Records = append(b.Records, values[i])
	}
	return b
}

// WithTTL sets the TTL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTL field is set to the value of the last call.
func (b *DNSRecordsetResourceStatusApplyConfiguration) WithTTL(value int32) *DNSRecordsetResourceStatusApplyConfiguration {
	b.TTL = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *DNSRecordsetResourceStatusApplyConfiguration) WithDescription(value string) *DNSRecordsetResourceStatusApplyConfiguration {
	b.Description = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *DNSRecordsetResourceStatusApplyConfiguration) WithStatus(value string) *DNSRecordsetResourceStatusApplyConfiguration {
	b.Status = &value
	return b
}
