/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
)

// DNSRecordsetFilterApplyConfiguration represents a declarative configuration of the DNSRecordsetFilter type for use
// with apply.
type DNSRecordsetFilterApplyConfiguration struct {
	Name        *apiv1alpha1.OpenStackName `json:"name,omitempty"`
	Type        *string                    `json:"type,omitempty"`
	TTL         *int32                     `json:"ttl,omitempty"`
	Description *string                    `json:"description,omitempty"`
}

// DNSRecordsetFilterApplyConfiguration constructs a declarative configuration of the DNSRecordsetFilter type for use with
// apply.
func DNSRecordsetFilter() *DNSRecordsetFilterApplyConfiguration {
	return &DNSRecordsetFilterApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DNSRecordsetFilterApplyConfiguration) WithName(value apiv1alpha1.OpenStackName) *DNSRecordsetFilterApplyConfiguration {
	b.Name = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *DNSRecordsetFilterApplyConfiguration) WithType(value string) *DNSRecordsetFilterApplyConfiguration {
	b.Type = &value
	return b
}

// WithTTL sets the TTL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTL field is set to the value of the last call.
func (b *DNSRecordsetFilterApplyConfiguration) WithTTL(value int32) *DNSRecordsetFilterApplyConfiguration {
	b.TTL = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *DNSRecordsetFilterApplyConfiguration) WithDescription(value string) *DNSRecordsetFilterApplyConfiguration {
	b.Description = &value
	return b
}
