---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: DNSRecordset
metadata:
  name: dnsrecordset-sample
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    name: sample.example.com.
    type: A
    records:
    - 1.2.3.4
    ttl: 3600
    description: Sample DNSRecordset
    dnsZoneRef: dnszone-sample
