/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DNSRecordsetLister helps list DNSRecordsets.
// All objects returned here must be treated as read-only.
type DNSRecordsetLister interface {
	// List lists all DNSRecordsets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.DNSRecordset, err error)
	// DNSRecordsets returns an object that can list and get DNSRecordsets.
	DNSRecordsets(namespace string) DNSRecordsetNamespaceLister
	DNSRecordsetListerExpansion
}

// dNSRecordsetLister implements the DNSRecordsetLister interface.
type dNSRecordsetLister struct {
	listers.ResourceIndexer[*apiv1alpha1.DNSRecordset]
}

// NewDNSRecordsetLister returns a new DNSRecordsetLister.
func NewDNSRecordsetLister(indexer cache.Indexer) DNSRecordsetLister {
	return &dNSRecordsetLister{listers.New[*apiv1alpha1.DNSRecordset](indexer, apiv1alpha1.Resource("dnsrecordset"))}
}

// DNSRecordsets returns an object that can list and get DNSRecordsets.
func (s *dNSRecordsetLister) DNSRecordsets(namespace string) DNSRecordsetNamespaceLister {
	return dNSRecordsetNamespaceLister{listers.NewNamespaced[*apiv1alpha1.DNSRecordset](s.ResourceIndexer, namespace)}
}

// DNSRecordsetNamespaceLister helps list and get DNSRecordsets.
// All objects returned here must be treated as read-only.
type DNSRecordsetNamespaceLister interface {
	// List lists all DNSRecordsets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.DNSRecordset, err error)
	// Get retrieves the DNSRecordset from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.DNSRecordset, error)
	DNSRecordsetNamespaceListerExpansion
}

// dNSRecordsetNamespaceLister implements the DNSRecordsetNamespaceLister
// interface.
type dNSRecordsetNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.DNSRecordset]
}
